// Code generated by hertz generator.

package main

import (
	"github.com/RanFeng/imc"
	"github.com/cloudwego/hertz/pkg/app/server"
	"hertz/demo/biz/conf"
	"hertz/demo/biz/infra"
	"hertz/demo/biz/mw/cors"
	"hertz/demo/biz/mw/time_log"
)

func main() {
	conf.Init()
	infra.InitMysql()
	infra.InitRedis()
	h := server.Default(server.WithHostPorts(conf.MustGet[string]("server_port")))
	h.Use(cors.CorsMw())
	h.Use(imc.InjectLogID())
	h.Use(time_log.TimeLog())
	//h.Use(imc.CommonMetrics())
	h.NoHijackConnPool = true
	register(h)
	h.Spin()
}
