// Code generated by hertz generator.

package handler

import (
	"context"
	"github.com/RanFeng/ierror"
	"github.com/RanFeng/ilog"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/common/utils"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// Ping .
func Ping(ctx context.Context, c *app.RequestContext) {
	ilog.EventError(ctx, ierror.NewIError(ierror.ErrUnknown, "ping error"), "ping")
	c.JSON(consts.StatusOK, utils.H{
		"message": "pong",
	})
}
